disabled_rules:
# - function_parameter_count
# - line_length
- trailing_whitespace
- private_over_fileprivate

opt_in_rules:
- first_where
- redundant_nil_coalesing
- switch_case_on_newline

excluded:
- Pods
- R.generated.swift
- .build
- Packages


line_length: 350

type_body_length:
- 300 # warning
- 400 # error

file_length:
    warning: 500
    error: 1000

variable_name:
    min_length: 2
    type_name:
    min_length: 2

